name: Setup PHP slow
runs:
  using: composite
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
        extensions: intl, mbstring, mysqli, pdo_mysql, pdo_pgsql, redis, xdebug
        tools: composer:v2, phpunit, php-cs-fixer, phpcs, phpstan
        coverage: xdebug
    - shell: bash
      run: sleep 45
