name: "[Windows] Build Phalcon"

on:
  - push
  - pull_request

env:
  # All versions should be declared here
  PHALCON_VERSION: '5.10.0'
  PHP_VERSION_LIST: '8.1, 8.2, 8.3, 8.4'
  ARCH_LIST: 'x64, x86'
  TS_LIST: 'nts, ts'

jobs:
  get-extension-matrix:
    runs-on: ubuntu-latest
    name: "Generate Extension Matrix"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get the extension matrix
        id: extension-matrix
        uses: php/php-windows-builder/extension-matrix@v1
        with:
          extension-url: https://github.com/xdebug/xdebug
          extension-ref: ${{ env.PHALCON_VERSION }}
          php-version-list: ${{ env.PHP_VERSION_LIST }}
          arch-list: ${{ env.ARCH_LIST }}
          ts-list: ${{ env.TS_LIST }}

  build:
    needs: get-extension-matrix
    runs-on: ${{ matrix.os }}
    name: "Build Phalcon (PHP ${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.arch }})"
    strategy:
      matrix: ${{fromJson(needs.get-extension-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate build folder
        run: |
          cd build/
          php gen-build.php
          cd ../
          pwd
          cp -v build/phalcon/*.* .

      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}


#      - name: Extract Phalcon Version
#        shell: powershell
#        run: |
#          chcp 65001
#          $r = Select-String -Path build/phalcon/php_phalcon.h -Pattern 'PHP_PHALCON_VERSION\s+"(.*)"'
#          $s = $r.Matches[0].Groups[1]
#          echo "$s"
#          $PhalconVersion = 'PHALCON_VERSION=' + $s
#          echo $PhalconVersion >> $env:GITHUB_ENV
#
#      - name: Setup PHP
#        id: setup-php
#        uses: php/setup-php-sdk@v0.11
#        with:
#          version: ${{matrix.php}}
#          arch: ${{matrix.arch}}
#          ts: ${{matrix.ts}}
#          deps: zlib

#      - name: Upload artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{env.ARTIFACT_NAME}}
#          path: |
#            ${{env.ARTIFACT}}
#            LICENSE.txt
