name: Runner
on: [push]
jobs:
  e2e-tests:
    name: Run
    runs-on: ${{ matrix.os }}    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025-vs2026]
    steps:
      - run: php -v || true
      - run: |
          $installerDir = Join-Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio" 'Installer'
          $vswherePath = Join-Path $installerDir 'vswhere.exe'
          if (-not (Test-Path $vswherePath)) {
              throw "vswhere is not available"
          }
          $MSVCDirectory = & $vswherePath -latest -products * -find "VC\Tools\MSVC"
          Get-ChildItem $MSVCDirectory
