name: Runner workflow
on:
  push:
jobs:
  runner:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ts: [nts, zts]
        php: [8.4, 8.5]
          
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: swoole-alpha
      - run: |
          php -v
          php -m
      
  
